In [1]:
%matplotlib inline


What is PyTorch?
================

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

-  NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
-  최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

Getting Started
---------------

Tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능합니다.



In [2]:
from __future__ import print_function
import torch

torch.__version__

'1.9.1+cu111'

초기화되지 않은 5x3 행렬을 생성합니다:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 1.1204e-38],
        [1.0745e-38, 9.5510e-39, 9.2756e-39],
        [9.8266e-39, 8.9082e-39, 8.9082e-39],
        [1.0194e-38, 9.1837e-39, 4.6837e-39],
        [9.9184e-39, 9.0000e-39, 1.0561e-38]])


무작위로 초기화된 행렬을 생성합니다:



In [4]:
x = torch.randn(5, 3) # normal distribution 정규분포에서 랜덤추출
print(x)
x = torch.rand(5, 3) # 0에서 1 사이의 값 랜덤 추출
print(x)

tensor([[-1.8421e+00,  5.9187e-01, -1.1135e+00],
        [ 1.2558e+00, -1.2799e-01,  1.9129e+00],
        [-8.7997e-02, -1.0283e+00, -2.6249e-01],
        [ 1.9530e+00,  3.2329e-01, -1.0901e+00],
        [ 1.2394e+00,  2.8754e-01,  1.2530e-03]])
tensor([[0.6872, 0.1183, 0.8381],
        [0.7605, 0.2544, 0.1359],
        [0.3587, 0.1139, 0.5167],
        [0.5131, 0.5814, 0.3740],
        [0.1974, 0.0425, 0.0467]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)  
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


데이터로부터 tensor를 직접 생성합니다:



In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만듭니다. 
이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.4079,  0.3981,  1.6976],
        [ 0.3109,  0.7748,  0.5501],
        [-0.1962, -1.2895, -2.1061],
        [-0.0880,  1.6825, -0.3708],
        [-2.1816,  0.2868, -1.4231]])


행렬의 크기를 구합니다:



In [9]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])



덧셈: 문법1

In [10]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[-1.4079,  0.3981,  1.6976],
        [ 0.3109,  0.7748,  0.5501],
        [-0.1962, -1.2895, -2.1061],
        [-0.0880,  1.6825, -0.3708],
        [-2.1816,  0.2868, -1.4231]])
tensor([[0.8812, 0.7416, 0.8334],
        [0.4855, 0.1459, 0.6207],
        [0.1795, 0.9907, 0.9139],
        [0.3750, 0.2766, 0.2516],
        [0.0959, 0.9549, 0.6481]])
tensor([[-0.5268,  1.1397,  2.5310],
        [ 0.7964,  0.9208,  1.1708],
        [-0.0167, -0.2988, -1.1922],
        [ 0.2870,  1.9591, -0.1192],
        [-2.0857,  1.2417, -0.7750]])


덧셈: 문법2



In [11]:
print(torch.add(x, y))

tensor([[-0.5268,  1.1397,  2.5310],
        [ 0.7964,  0.9208,  1.1708],
        [-0.0167, -0.2988, -1.1922],
        [ 0.2870,  1.9591, -0.1192],
        [-2.0857,  1.2417, -0.7750]])


덧셈: 결과 tensor를 인자로 제공


In [12]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result) # 결과값이 tensor로 들어가게 된다.
print(result)

tensor([[9.2755e-39, 1.0561e-38, 1.1204e-38],
        [1.0745e-38, 9.5510e-39, 9.2756e-39],
        [9.8266e-39, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39]])
tensor([[-0.5268,  1.1397,  2.5310],
        [ 0.7964,  0.9208,  1.1708],
        [-0.0167, -0.2988, -1.1922],
        [ 0.2870,  1.9591, -0.1192],
        [-2.0857,  1.2417, -0.7750]])


덧셈: 바꿔치기(In-place) 방식


In [13]:
# adds x to y
print(y)
y.add_(x)
print(y)

tensor([[0.8812, 0.7416, 0.8334],
        [0.4855, 0.1459, 0.6207],
        [0.1795, 0.9907, 0.9139],
        [0.3750, 0.2766, 0.2516],
        [0.0959, 0.9549, 0.6481]])
tensor([[-0.5268,  1.1397,  2.5310],
        [ 0.7964,  0.9208,  1.1708],
        [-0.0167, -0.2988, -1.1922],
        [ 0.2870,  1.9591, -0.1192],
        [-2.0857,  1.2417, -0.7750]])


<div class="alert alert-info"><h4>Note</h4><p>바꿔치기(In-place) 방식으로 tensor의 값을 변경하는 연산은 _ 를 접미사로 갖습니다.<p>
예: x.copy_(y), x.t_() 는 x 를 변경합니다.

<p>
NumPy스러운 인덱싱 표기 방법을 사용할 수도 있습니다!


In [14]:
print(x)
print(x[:, 1])

tensor([[-1.4079,  0.3981,  1.6976],
        [ 0.3109,  0.7748,  0.5501],
        [-0.1962, -1.2895, -2.1061],
        [-0.0880,  1.6825, -0.3708],
        [-2.1816,  0.2868, -1.4231]])
tensor([ 0.3981,  0.7748, -1.2895,  1.6825,  0.2868])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다:


In [15]:
x = torch.randn(4, 4)
print(x)

y = x.view(16)
z = y.view(-1, 2)  # the size -1 is inferred from other dimensions
print(y)
print(z)
print(y.size(), z.size())

tensor([[ 1.9102, -0.4675, -0.7947, -0.0723],
        [-1.9360, -1.9146, -0.8659, -0.7385],
        [-0.3092,  1.7915,  0.4562,  0.4796],
        [ 0.2189,  0.5299, -0.0214, -0.0152]])
tensor([ 1.9102, -0.4675, -0.7947, -0.0723, -1.9360, -1.9146, -0.8659, -0.7385,
        -0.3092,  1.7915,  0.4562,  0.4796,  0.2189,  0.5299, -0.0214, -0.0152])
tensor([[ 1.9102, -0.4675],
        [-0.7947, -0.0723],
        [-1.9360, -1.9146],
        [-0.8659, -0.7385],
        [-0.3092,  1.7915],
        [ 0.4562,  0.4796],
        [ 0.2189,  0.5299],
        [-0.0214, -0.0152]])
torch.Size([16]) torch.Size([8, 2])


만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.



In [16]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())


tensor([-0.3053])
<class 'torch.Tensor'> <class 'float'>
-0.3052506446838379


**읽을 거리:**


  전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등과 같은 100가지 이상의 Tensor 연산은
  `여기 <http://pytorch.org/docs/torch>` 에 설명되어 있습니다.

NumPy 변환(Bridge)
------------

Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(CPU 상의) Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

- Torch Tensor를 NumPy 배열로 변환하기



In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값이 어떻게 변하는지 확인해보세요.



In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


 - NumPy 배열을 Torch Tensor로 변환하기  
 
NumPy(np) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.



In [21]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의) 반대 변환도 지원합니다.

CUDA Tensors
------------

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.



In [22]:
import torch

# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.

x = torch.rand(4,4)
if torch.cuda.is_available():
    device = "cuda:0" # torch.device("cuda:0")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    print(y)


    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.1051, 1.5517, 1.1135, 1.7938],
        [1.3002, 1.1661, 1.7746, 1.9607],
        [1.0176, 1.5795, 1.1660, 1.9133],
        [1.2801, 1.7928, 1.6554, 1.4061]], device='cuda:0')
tensor([[1.1051, 1.5517, 1.1135, 1.7938],
        [1.3002, 1.1661, 1.7746, 1.9607],
        [1.0176, 1.5795, 1.1660, 1.9133],
        [1.2801, 1.7928, 1.6554, 1.4061]], dtype=torch.float64)


In [23]:
x = x.cuda()