# 불러오기

In [1]:
import joblib
data = joblib.load('../data/nsmc.pkl')

In [2]:
data['words']

['13구역/NNP',
 '가/VV',
 '가/VX',
 '가능/NNG',
 '가볍/VA',
 '가슴/NNG',
 '가족/NNG',
 '가지/NNB',
 '가지/VV',
 '가치/NNG',
 '각본/NNG',
 '간/NNB',
 '간/NNG',
 '간만/NNG',
 '갈등/NNG',
 '감/NNG',
 '감독/NNG',
 '감동/NNG',
 '감사/NNG',
 '감성/NNG',
 '감정/NNG',
 '강/NNP',
 '강요/NNG',
 '같/VA',
 '개/NNB',
 '개/NNG',
 '개그맨/NNG',
 '개념/NNG',
 '개봉/NNG',
 '개뿔/NNG',
 '개연/NNG',
 '개인/NNG',
 '개판/NNG',
 '걍/NNG',
 '거/NNB',
 '거기/NP',
 '거부/NNG',
 '거슬리/VV',
 '거장/NNG',
 '걱정/NNG',
 '걸/VV',
 '걸리/VV',
 '걸작/NNG',
 '검술/NNG',
 '겁나/VV',
 '것/NNB',
 '게/NNG',
 '게임/NNG',
 '결국/NNG',
 '결말/NNG',
 '고추/NNG',
 '곳/NNG',
 '곳곳/NNG',
 '공감/NNG',
 '공부/NNG',
 '공포/NNG',
 '곽지민/NNP',
 '관/NNG',
 '관객/NNG',
 '관계/NNG',
 '관람/NNG',
 '관심/NNG',
 '괜찮/VA',
 '괜찮/VV',
 '교훈/NNG',
 '구성/NNG',
 '구하/VV',
 '국산/NNG',
 '군/NNG',
 '군대/NNG',
 '굿/NNG',
 '귀신/NNG',
 '귀엽/VA',
 '그/NP',
 '그거/NP',
 '그것/NP',
 '그녀/NP',
 '그때/NNG',
 '그래픽/NNG',
 '그러/VV',
 '그렇/VA',
 '그리/VV',
 '그림/NNG',
 '그립/VA',
 '극/NNG',
 '극장/NNG',
 '급/NNG',
 '기/NNG',
 '기대/NNG',
 '기독교/NNG',
 '기분/NNG',
 '기억/NNG',
 '기존/NNG',
 '긴장/NNG',
 '긴

In [3]:
locals().update(data) # locals 지역변수: 변수들을 사전형태로 만들어줌.

In [4]:
words

['13구역/NNP',
 '가/VV',
 '가/VX',
 '가능/NNG',
 '가볍/VA',
 '가슴/NNG',
 '가족/NNG',
 '가지/NNB',
 '가지/VV',
 '가치/NNG',
 '각본/NNG',
 '간/NNB',
 '간/NNG',
 '간만/NNG',
 '갈등/NNG',
 '감/NNG',
 '감독/NNG',
 '감동/NNG',
 '감사/NNG',
 '감성/NNG',
 '감정/NNG',
 '강/NNP',
 '강요/NNG',
 '같/VA',
 '개/NNB',
 '개/NNG',
 '개그맨/NNG',
 '개념/NNG',
 '개봉/NNG',
 '개뿔/NNG',
 '개연/NNG',
 '개인/NNG',
 '개판/NNG',
 '걍/NNG',
 '거/NNB',
 '거기/NP',
 '거부/NNG',
 '거슬리/VV',
 '거장/NNG',
 '걱정/NNG',
 '걸/VV',
 '걸리/VV',
 '걸작/NNG',
 '검술/NNG',
 '겁나/VV',
 '것/NNB',
 '게/NNG',
 '게임/NNG',
 '결국/NNG',
 '결말/NNG',
 '고추/NNG',
 '곳/NNG',
 '곳곳/NNG',
 '공감/NNG',
 '공부/NNG',
 '공포/NNG',
 '곽지민/NNP',
 '관/NNG',
 '관객/NNG',
 '관계/NNG',
 '관람/NNG',
 '관심/NNG',
 '괜찮/VA',
 '괜찮/VV',
 '교훈/NNG',
 '구성/NNG',
 '구하/VV',
 '국산/NNG',
 '군/NNG',
 '군대/NNG',
 '굿/NNG',
 '귀신/NNG',
 '귀엽/VA',
 '그/NP',
 '그거/NP',
 '그것/NP',
 '그녀/NP',
 '그때/NNG',
 '그래픽/NNG',
 '그러/VV',
 '그렇/VA',
 '그리/VV',
 '그림/NNG',
 '그립/VA',
 '극/NNG',
 '극장/NNG',
 '급/NNG',
 '기/NNG',
 '기대/NNG',
 '기독교/NNG',
 '기분/NNG',
 '기억/NNG',
 '기존/NNG',
 '긴장/NNG',
 '긴

In [5]:
import pandas as pd
nsmc = pd.read_csv('../data/ratings_train.txt', sep='\t')

In [6]:
type(nsmc.label)

pandas.core.series.Series

In [7]:
x = dtm

In [8]:
y = nsmc.label.values[:2000] # numpy의 array 형식읋 변경

# 데이터 분할

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
# x = dtm
# y = nsmc.label.values[:2000]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1984)

# 로지스틱 회귀분석 실습

# 모형 정의

In [11]:
import tensorflow as tf

In [12]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

# 설정

In [13]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 훈련

In [14]:
model.fit(x_train.A, y_train, epochs=3)

Epoch 1/3
50/50 [==============================] - 1s 3ms/step - loss: 0.6945 - accuracy: 0.5315
Epoch 2/3
50/50 [==============================] - 0s 3ms/step - loss: 0.6768 - accuracy: 0.6575
Epoch 3/3
50/50 [==============================] - 0s 3ms/step - loss: 0.6606 - accuracy: 0.7008


# 테스트

In [15]:
model.evaluate(x_test.A, y_test)

13/13 [==============================] - 0s 3ms/step - loss: 0.6664 - accuracy: 0.6600


[0.6663515567779541, 0.6600000262260437]

# 저장

In [16]:
model.save('../data/nsmc.krs')

INFO:tensorflow:Assets written to: nsmc.krs\assets


# 가중치 분석

# 모형 불러오기

In [17]:
import tensorflow as tf
model = tf.keras.models.load_model('../data/nsmc.krs')

# 파라미터

In [18]:
w, b = model.weights

# 단어별 가중치 표

In [19]:
import pandas as pd
word_sent = pd.DataFrame({'토큰': words, '가중치': w.numpy().flat})

# 부정단어

In [20]:
word_sent.sort_values('가중치').head()

토큰       가중치
331    뭐/NP -0.141692
206   돈/NNG -0.137114
745   작/NNG -0.117557
515  실망/NNG -0.116567
423   산/NNG -0.112721

# 긍정단어

In [21]:
word_sent.sort_values('가중치').tail()

토큰       가중치
881  최고/NNG  0.114694
578   어리/VA  0.117281
503  시절/NNG  0.126321
304  명작/NNG  0.128982
801    좋/VA  0.149576

- CSR 방식으로 압축된 문서 단어 행렬을 COO 방식으로 변환

In [22]:
x_coo = x_train.tocoo()

- 행 번호

In [23]:
x_coo.row

array([   0,    0,    0, ..., 1599, 1599, 1599])

- 열 번호

In [24]:
x_coo.col

array([  1, 119, 140, ..., 754, 951, 952])

- 내용

In [25]:
x_coo.data

array([1, 1, 1, ..., 1, 1, 7], dtype=int64)

- 행 번호와 열 번호를 컬럼으로 합친다.

In [26]:
import numpy as np
index = np.column_stack([x_coo.row, x_coo.col]); index

array([[   0,    1],
       [   0,  119],
       [   0,  140],
       ...,
       [1599,  754],
       [1599,  951],
       [1599,  952]])

## 순서가 섞여있는 경우 -> 텐서플로에서 받아주지를 못함

- 텐서플로의 SparseTensor로 변환

In [27]:
x_train_sparse = tf.SparseTensor(index, x_coo.data, x_coo.shape)

- 행과 열 번호를 정렬

In [28]:
x_train_sparse = tf.sparse.reorder(x_train_sparse)

- 모형 훈련에 사용한다

In [29]:
model.fit(x_train_sparse, y_train, epochs=1)

50/50 [==============================] - 1s 4ms/step - loss: 0.6451 - accuracy: 0.7456


### 데이터가 큰 경우에는 압축을 풀지 않고, 텐서플로의 희소행렬 형식으로 바꿔서 넣어줌.

# Early Stopping 실습

- validation_split으로 중간 테스트에 사용할 validation data의 비율을 지정한다.
- callbacks에 EarlyStopping을 추가하면 각 에포크 끝마다 성능을 테스트하여 중단 여부를 결정한다.

In [30]:
model.fit(x_train.A, y_train, epochs=100, validation_split=0.1,
          callbacks=[tf.keras.callbacks.EarlyStopping(monitor='val_accuracy')])

Epoch 1/100
45/45 [==============================] - 2s 43ms/step - loss: 0.6320 - accuracy: 0.7625 - val_loss: 0.6196 - val_accuracy: 0.8125
Epoch 2/100
45/45 [==============================] - 0s 5ms/step - loss: 0.6201 - accuracy: 0.7757 - val_loss: 0.6118 - val_accuracy: 0.8375
Epoch 3/100
45/45 [==============================] - 0s 5ms/step - loss: 0.6089 - accuracy: 0.7896 - val_loss: 0.6039 - val_accuracy: 0.8313
