## 210928 실습

In [1]:
import torch

if torch.cuda.is_available(): # 현재 파이썬이 실행되고 있는 환경에서 torch 모듈을 이용할 때 GPU를 이용할 수 있는지 확인하는 함수
    DEVICE = torch.device('cuda') # 참이면 'cuda' 이용
else:
    DEVICE = torch.device('cpu') # 거짓이면 'cpu' 이용

x = torch.tensor([[2.0, 3.0]], requires_grad=False)
y = torch.tensor([[1.0]], requires_grad=False)

w1 = torch.tensor([[0.11, 0.21],
                   [0.12, 0.08]], requires_grad=True)
w2 = torch.tensor([[0.14],
                   [0.15]], requires_grad=True)

# 학습 정도를 결정하는 learning_rate 설정
learning_rate = 0.05                                         
for t in range(2):
    hidden = x @ w1 #.T
    print(hidden)
    y_pred = hidden @ w2
    print(y_pred)
    
    loss = torch.sum(((y_pred - y).pow(2))*(1/2))
    if t % 100 == 0:
        print("Iteration: ", t, "\t", "Loss: ", loss.item()) # loss.item(): tensor type을 Python number type으로 바꿔줌
    print(w1)
    print(w2)
    print('y_pred: ', y_pred)
    print(str(t+1)+" step loss: ", loss)
    
    if t == 0:
        loss.backward()
        with torch.no_grad(): # 아래 코드들은 Gradient를 추가 계산하지 않고 고정시킨 상태에서 실행됨                                     
            w1 -= learning_rate * w1.grad # w1 Update
            w2 -= learning_rate * w2.grad # w2 Update              

            w1.grad.zero_() # w1에 저장되어 있는 Gradient를 0으로 초기화             
            w2.grad.zero_() # w2에 저장되어 있는 Gradient를 0으로 초기화

tensor([[0.8500, 0.4800]], grad_fn=<MmBackward>)
tensor([[0.1910]], grad_fn=<MmBackward>)
Iteration:  0 	 Loss:  0.327240526676178
tensor([[0.1100, 0.2100],
        [0.1200, 0.0800]], requires_grad=True)
tensor([[0.1400],
        [0.1500]], requires_grad=True)
y_pred:  tensor([[0.1910]], grad_fn=<MmBackward>)
1 step loss:  tensor(0.3272, grad_fn=<SumBackward0>)
tensor([[0.9236, 0.5589]], grad_fn=<MmBackward>)
tensor([[0.2557]], grad_fn=<MmBackward>)
tensor([[0.1213, 0.2270],
        [0.1321, 0.0982]], requires_grad=True)
tensor([[0.1744],
        [0.1694]], requires_grad=True)
y_pred:  tensor([[0.2557]], grad_fn=<MmBackward>)
2 step loss:  tensor(0.2770, grad_fn=<SumBackward0>)
